### ISSUE TITLE
thirdperson

### ISSUE THREAD

**Issue by Radeon0078** [canedoly/ChadAlphaMales#1]
dont know if you even care but thirdperson crashes

**Comment by canedoly** [comment]
yeah ik about it, disabling every option under the thirdperson section seems to work. But i'll check what's wrong

**Comment by Radeon0078** [comment]
> yeah ik about it, disabling every option under the thirdperson section seems to work. But i'll check what's wrong

Thanks also it would be cool if you could keep cam alive and maybe add shit to it. (i want fware to die its somehow worse than cam)

**Comment by canedoly** [comment]
> Thanks also it would be cool if you could keep cam alive and maybe add shit to it. (i want fware to die its somehow worse than cam)

Keeping cam alive shouldn't be hard. Adding new stuff also shouldn't be hard, but I would be limited to things already present in fedoraware or somewhat simple

Also when I used cam it seemed ok, worse than fedoraware imo but many people say it's better, could you tell me which stuff seem to do better than fedoraware?

**Comment by Radeon0078** [comment]
> > Thanks also it would be cool if you could keep cam alive and maybe add shit to it. (i want fware to die its somehow worse than cam)
> 
> Keeping cam alive shouldn't be hard. Adding new stuff also shouldn't be hard, but I would be limited to things already present in fedoraware or somewhat simple
> 
> Also when I used cam it seemed ok, worse than fedoraware imo but many people say it's better, could you tell me which stuff seem to do better than fedoraware?
> 
> EDIT: If you find any issues, please report them as I barely use this cheat.
Do you have like a discord just so i can foward and report shit way faster?

**Comment by Radeon0078** [comment]
> > Thanks also it would be cool if you could keep cam alive and maybe add shit to it. (i want fware to die its somehow worse than cam)
> 
> Keeping cam alive shouldn't be hard. Adding new stuff also shouldn't be hard, but I would be limited to things already present in fedoraware or somewhat simple
> 
> Also when I used cam it seemed ok, worse than fedoraware imo but many people say it's better, could you tell me which stuff seem to do better than fedoraware?
> 
> EDIT: If you find any issues, please report them as I barely use this cheat.

Projectile aimbot seems to do way better. also do you have a discord where i can report stuff faster?

**Comment by canedoly** [comment]
> > > Thanks also it would be cool if you could keep cam alive and maybe add shit to it. (i want fware to die its somehow worse than cam)
> > 
> > 
> > Keeping cam alive shouldn't be hard. Adding new stuff also shouldn't be hard, but I would be limited to things already present in fedoraware or somewhat simple
> > Also when I used cam it seemed ok, worse than fedoraware imo but many people say it's better, could you tell me which stuff seem to do better than fedoraware?
> > EDIT: If you find any issues, please report them as I barely use this cheat.
> 
> Projectile aimbot seems to do way better. also do you have a discord where i can report stuff faster?

Yeah, ig you could message me bugs/crashes here zap#2764
and about projectile aimbot, i saw your video about rijin vs cam, and the pasted strafe prediction/projectile aimbot seem to do way better than current one in fedoraware and the source they pasted from
